/*
 * By Mas Elkhanza
 */

package gemini;

import java.awt.Cursor;
import com.google.cloud.speech.v1.RecognitionAudio;
import com.google.cloud.speech.v1.RecognitionConfig;
import com.google.cloud.speech.v1.SpeechClient;
import com.google.cloud.speech.v1.SpeechRecognitionResult;
import com.google.cloud.speech.v1.SpeechRecognitionAlternative;
import com.google.cloud.speech.v1.RecognizeResponse;
import java.nio.file.Path;
import com.google.protobuf.ByteString;
import java.awt.event.ActionEvent;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.IOException;
import simrskhanza.DlgRawatJalan;
/**
 *
 * @author perpustakaan
 */
public final class ChatGemini extends javax.swing.JDialog {
    private String reply="";
    private final GeminiService geminiService = new GeminiService();
    private final DlgRawatJalan kirimSOAPIE = new DlgRawatJalan(null,false);
    //private static final JsonFactory JSON_FACTORY = new GsonFactory.getDefaultInstance();

    /** Creates new form DlgRujuk
     * @param parent
     * @param modal */
    public ChatGemini(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        TabRawat = new javax.swing.JTabbedPane();
        internalFrame7 = new widget.InternalFrame();
        scrollInput5 = new widget.ScrollPane();
        FormInput6 = new widget.PanelBiasa();
        jLabel255 = new widget.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        typeField = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        BtnKeluar = new widget.Button();
        jLabel256 = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ BERYU AI CHAT ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 50, 50)));
        internalFrame1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        internalFrame1.setName("internalFrame1");
        internalFrame1.setPreferredSize(new java.awt.Dimension(550, 500));
        internalFrame1.setLayout(new java.awt.BorderLayout());

        TabRawat.setBackground(new java.awt.Color(51, 153, 255));
        TabRawat.setForeground(new java.awt.Color(50, 50, 50));
        TabRawat.setName("TabRawat"); // NOI18N
        TabRawat.setPreferredSize(new java.awt.Dimension(457, 480));

        internalFrame7.setBorder(null);
        internalFrame7.setName("internalFrame7"); // NOI18N
        internalFrame7.setPreferredSize(new java.awt.Dimension(102, 480));
        internalFrame7.setLayout(new java.awt.BorderLayout(1, 1));

        scrollInput5.getVerticalScrollBar().setUnitIncrement(50);
        scrollInput5.setName("scrollInput5"); // NOI18N
        scrollInput5.setPreferredSize(new java.awt.Dimension(102, 557));

        FormInput6.setBackground(new java.awt.Color(51, 153, 255));
        FormInput6.setBorder(null);
        FormInput6.setName("FormInput6"); // NOI18N
        FormInput6.setPreferredSize(new java.awt.Dimension(700, 500));
        FormInput6.setLayout(null);

        jLabel255.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel255.setText("CHAT WITH AI");
        jLabel255.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel255.setName("jLabel255"); // NOI18N
        FormInput6.add(jLabel255);
        jLabel255.setBounds(20, 0, 110, 20);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        messageField.setEditable(false);
        messageField.setColumns(20);
        messageField.setRows(5);
        messageField.setName("messageField"); // NOI18N
        jScrollPane1.setViewportView(messageField);

        FormInput6.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 510, 280);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        typeField.setColumns(20);
        typeField.setRows(5);
        typeField.setName("typeField"); // NOI18N
        jScrollPane2.setViewportView(typeField);

        FormInput6.add(jScrollPane2);
        jScrollPane2.setBounds(20, 340, 510, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("SEND");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FormInput6.add(jButton1);
        jButton1.setBounds(20, 400, 150, 30);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        FormInput6.add(BtnKeluar);
        BtnKeluar.setBounds(180, 400, 130, 30);

        jLabel256.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel256.setText("Tulis pertanyaan di bawah:");
        jLabel256.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel256.setName("jLabel256"); // NOI18N
        FormInput6.add(jLabel256);
        jLabel256.setBounds(20, 310, 200, 20);

        scrollInput5.setViewportView(FormInput6);

        internalFrame7.add(scrollInput5, java.awt.BorderLayout.CENTER);

        TabRawat.addTab("", internalFrame7);

        internalFrame1.add(TabRawat, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);
        internalFrame1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reply = typeField.getText();
        if(reply.contains("exit")){
            try{
            messageField.setText("");
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
            
        }
        }else{
        try{
            messageField.append("you : " + reply);
            String response = geminiService.generateResponse(reply);
            messageField.append("\nBeryu AI: " + response +"\n");
            typeField.setText("");
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
            
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ChatGemini dialog = new ChatGemini(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.PanelBiasa FormInput6;
    private javax.swing.JTabbedPane TabRawat;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame7;
    private javax.swing.JButton jButton1;
    private widget.Label jLabel255;
    private widget.Label jLabel256;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageField;
    private widget.ScrollPane scrollInput5;
    private javax.swing.JTextArea typeField;
    // End of variables declaration//GEN-END:variables

    public void setTampil(){
       TabRawat.setSelectedIndex(1);
    }
    
    public String SOAPIE(){
        String str = messageField.getText();
        int startSub = str.indexOf("**S (Subjective):**")+"**S (Subjective):**".length();
        int endSub =str.lastIndexOf("**O (Objective):**");
        String subOut = str.substring(startSub,endSub);
        //kirimSOAPIE.inputText(subOut);
        System.out.println(subOut);
        return null;
    }

}
